checks:
    python:
        code_rating: true
        duplicate_code: true
        variables_unpacking_non_sequence: true
        variables_unused_argument: true
        variables_unused_variable: true
        variables_unused_import: true
        variables_unused_wildcard_import: true
        variables_used_before_assignment: true
        variables_undefined_variable: true
        variables_undefined_loop_variable: true
        variables_unbalanced_tuple_unpacking: true
        variables_redefined_outer_name: true
        variables_redefined_builtin: true
        typecheck_redundant_keyword_arg: true
        typecheck_unexpected_keyword_arg: true
        typecheck_too_many_function_args: true
        typecheck_not_callable: true
        typecheck_no_value_for_parameter: true
        newstyle_bad_super_call: true
        open_mode_bad_open_mode: true
        string_bad_format_character: true
        string_bad_format_string_key: true
        string_bad_str_strip_call: true
        basic_dangerous_default_value: true
        basic_duplicate_argument_name: true
        basic_duplicate_key: true
        basic_empty_docstring: true
        basic_eval_used: true
        basic_function_redefined: true
        basic_init_is_generator: true
        basic_invalid_name:
            functions: '[a-z_][a-z0-9_]{2,30}$'
            variables: '[a-z_][a-z0-9_]{2,30}$'
            whitelisted_names: 'i,j,k,ex,Run,_'
            constants: '(([A-Z_][A-Z0-9_]*)|(__.*__))$'
            attributes: '[a-z_][a-z0-9_]{2,30}$'
            arguments: '[a-z_][a-z0-9_]{2,30}$'
            class_attributes: '([A-Za-z_][A-Za-z0-9_]{2,30}|(__.*__))$'
            inline_vars: '[A-Za-z_][A-Za-z0-9_]*$'
            classes: '[A-Z_][a-zA-Z0-9]+$'
            modules: '(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$'
            methods: '[a-z_][a-z0-9_]{2,30}$'
        basic_lost_exception: true
        basic_missing_module_attribute: true
        basic_nonexistent_operator: true
        basic_not_in_loop: true
        basic_old_raise_syntax: true
        basic_return_arg_in_generator: true
        basic_return_in_init: true
        basic_return_outside_function: true
        basic_star_args: true
        basic_unnecessary_lambda: true
        basic_unnecessary_pass: true
        basic_unreachable: true
        basic_useless_else_on_loop: true
        classes_attribute_defined_outside_init: true
        classes_no_self_argument: true
        exceptions_pointless_except: true
        format_backtick: true
        typecheck_no_member: true
        typecheck_missing_kwoa: true
        typecheck_duplicate_keyword_arg: true
        typecheck_maybe_no_member: true
        imports_deprecated_module: true
        format_old_ne_operator: true
        design_abstract_class_little_used: true
        basic_missing_docstring: true
        basic_exec_used: true
        miscellaneous_fixme: true
        imports_wildcard_import: true
        format_unnecessary_semicolon: true
        format_trailing_whitespace: true
        format_multiple_statements: true
        format_mixed_indentation: true
        format_bad_whitespace: true
        format_bad_indentation:
            indentation: '4 spaces'
        classes_protected_access: true
        classes_no_self_use: true
        variables_no_name_in_module: true
        string_too_many_format_args: true
        string_constant_anomalous_backslash_in_string: true
        imports_reimported: true
        imports_import_self: true
        logging_format_truncated: true
        logging_too_few_args: true
        logging_too_many_args: true
        logging_unsupported_format: true
        string_format_needs_mapping: true
        string_missing_format_string_key: true
        string_mixed_format_string: true
        string_too_few_format_args: true
        string_truncated_format_string: true
        string_unused_format_string_key: true
        imports_import_error: true
        imports_cyclic_import: true
        exceptions_raising_string: true
        exceptions_raising_non_exception: true
        exceptions_raising_bad_type: true
        exceptions_notimplemented_raised: true
        exceptions_bad_except_order: true
        exceptions_catching_non_exception: true
        classes_non_iterator_returned: true
        classes_no_method_argument: true
        format_superfluous_parens: true
        imports_relative_import: true
        exceptions_broad_except: true
        classes_super_init_not_called: true
        classes_no_init: true
        classes_bad_staticmethod_argument: true

filter:
    excluded_paths:
        - '*/tests/*'
        - 'tests/*'
tools:
    external_code_coverage: true
before_commands:
    - sudo apt-get install -y python-argparse python-bottle python-lxml python-mysqldb python-redis python-tz python-zmq
    - pip install isodate