language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install -qq python-argparse python-bottle python-lxml python-mysqldb python-redis python-tz libzmq-dev
virtualenv:
  system_site_packages: true
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: "pip install -r requirements.txt"
# command to run tests, e.g. python setup.py test
script: python tests/test.py