language: python
python:
  - "2.7"
services:
  - redis-server
before_install:
  # See: https://github.com/travis-ci/travis-ci/issues/3106
  - sudo apt-get remove libzmq3
  - sudo rm /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
  - sudo apt-get install -qq python-argparse python-bottle python-lxml python-mysqldb python-redis python-tz python-zmq
virtualenv:
  system_site_packages: true
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  #- "pip install -r requirements.txt"
  - pip install isodate
  - pip install coveralls
  - pip install scrutinizer-ocular
before_script:
  - cp config/serviceinfo-unittest.travis.yaml config/serviceinfo-unittest.yaml
  - mysql -e 'create database rdt_iff_test;'
  - mysql -u travis rdt_iff_test < doc/testdata/iff-testset.sql
script: coverage run --source serviceinfo -m py.test
after_success:
  - coveralls
  - ocular --data-file ".coverage"